import { ivItem } from '../lib.js';

// Noisy time series with a stated generating model; the truth is the noise-free model
// value at a future time. Linear, exponential (constant % growth) or linear + seasonal.
const model = (m, t) => (m.kind === 'linear' ? m.a + m.b * t : m.kind === 'exp' ? m.a * m.g ** t : m.a + m.b * t + m.amp * Math.sin((2 * Math.PI * t) / m.period));

const fam = {
  id: 'series',
  section: 'iv',
  title: 'Extrapolate a noisy time series',
  skill: 'Fit the trend by eye through the noise, extrapolate it, and widen for how far you extrapolate',
  levels: [3, 4, 5],
  generate(rng, { difficulty = 3 } = {}) {
    const T = rng.int(24, 36), h = rng.int(4, 12), tStar = T + h;
    let m, sigma, desc;
    if (difficulty === 3) {
      const b = +(rng.float(0.5, 3) * (rng.chance(0.7) ? 1 : -1)).toFixed(2);
      const a = rng.int(20, 80) + (b < 0 ? Math.ceil(-b * tStar) + 10 : 0);
      m = { kind: 'linear', a, b }; sigma = +(Math.abs(b) * rng.float(1.5, 4)).toFixed(2);
      desc = 'a straight-line trend plus random noise';
    } else if (difficulty === 4) {
      m = { kind: 'exp', a: rng.int(10, 50), g: +rng.float(1.02, 1.06).toFixed(3) }; sigma = +rng.float(0.03, 0.07).toFixed(3);
      desc = 'a trend growing by a constant percentage each step, times random noise';
    } else {
      const b = +rng.float(0.3, 2).toFixed(2);
      m = { kind: 'seasonal', a: rng.int(30, 70), b, amp: rng.int(5, 15), period: rng.pick([6, 12]) }; sigma = +rng.float(1, 3).toFixed(2);
      desc = `a straight-line trend plus a repeating cycle of length ${m.period}, plus random noise`;
    }
    const points = Array.from({ length: T }, (_, i) => {
      const t = i + 1, base = model(m, t);
      const y = m.kind === 'exp' ? base * Math.exp(rng.normal(0, sigma)) : base + rng.normal(0, sigma);
      return [t, Math.round(y * 100) / 100];
    });
    const truth = model(m, tStar);
    // prediction error of an OLS fit, doubled for fitting by eye
    const tbar = (T + 1) / 2, Sxx = points.reduce((s, [t]) => s + (t - tbar) ** 2, 0);
    const se = Math.sqrt(1 / T + (tStar - tbar) ** 2 / Sxx);
    const belief = m.kind === 'exp'
      ? { kind: 'lognormal', sd: Number(Math.max(2 * sigma * se, 0.03).toPrecision(2)) }
      : { kind: 'normal', sd: Number(Math.max(2 * sigma * se, 0.02 * truth, m.kind === 'seasonal' ? 0.1 * m.amp : 0).toPrecision(2)) };
    const visual = { type: 'series', points, target: tStar, xLabel: 't', yLabel: 'value', label: `A noisy series observed at t = 1 to ${T}` };
    const trendText = m.kind === 'linear' ? `The trend is ${m.a} ${m.b < 0 ? '−' : '+'} ${Math.abs(m.b)}·t.` : m.kind === 'exp' ? `The trend is ${m.a} × ${m.g}^t (growth ${((m.g - 1) * 100).toFixed(1)}% per step).` : `The pattern is ${m.a} + ${m.b}·t + ${m.amp}·sin(2πt/${m.period}).`;
    return ivItem(fam, rng, difficulty, {
      text: `The chart shows a quantity observed at t = 1 to ${T}, generated by ${desc}. Estimate the noise-free ${m.kind === 'seasonal' ? 'pattern (trend plus cycle)' : 'trend'} value at t = ${tStar}.`,
      visual, truth, unit: '',
      coach: { exact: false, belief, note: `Fitting by eye and extrapolating ${h} steps beyond the data: expect an error of about ${belief.kind === 'normal' ? `±${belief.sd}` : `±${Math.round(belief.sd * 100)}%`}.` },
      steps: [
        { say: m.kind === 'linear' ? 'Read the level near the start and near the end of the data (average a few points each) to get the slope.' : m.kind === 'exp' ? 'Read how many steps the series takes to double (or grow by half), which gives the growth rate.' : `Average over one full cycle (${m.period} points) at the start and end to get the trend, then add where t = ${tStar} sits in the cycle.`, why: 'Averaging several points cancels noise; two well-separated averages fix a line.' },
        { say: `${trendText} At t = ${tStar}: ${truth.toFixed(2)}.`, why: 'The generating model, evaluated without noise.' },
      ],
      hints: ['Ignore single points; average clusters at the start and at the end.', `How far beyond the data is t = ${tStar}? Error grows with that distance.`],
      params: { scenario: m.kind, model: m, noise: sigma, points, target: tStar },
    });
  },
  // Independent checks: the model value recomputed from params, and a least-squares fit
  // of the plotted points lands within 5 standard errors of it (the item is answerable).
  verify(item) {
    const m = item.params.model, t = item.params.target, pts = item.prompt.visual.points;
    const direct = m.kind === 'linear' ? m.b * t + m.a : m.kind === 'exp' ? Math.exp(Math.log(m.a) + t * Math.log(m.g)) : m.a + m.b * t + m.amp * Math.sin((2 * Math.PI * t) / m.period);
    const X = pts.map(([tt]) => (m.kind === 'seasonal' ? [1, tt, Math.sin((2 * Math.PI * tt) / m.period), Math.cos((2 * Math.PI * tt) / m.period)] : [1, tt]));
    const y = pts.map(([, v]) => (m.kind === 'exp' ? Math.log(v) : v));
    const beta = ols(X, y);
    const xs = m.kind === 'seasonal' ? [1, t, Math.sin((2 * Math.PI * t) / m.period), Math.cos((2 * Math.PI * t) / m.period)] : [1, t];
    let fit = xs.reduce((s, v, i) => s + v * beta[i], 0);
    if (m.kind === 'exp') fit = Math.exp(fit);
    const resid = y.map((v, i) => v - X[i].reduce((s, x, j) => s + x * beta[j], 0));
    const s = Math.sqrt(resid.reduce((a, r) => a + r * r, 0) / (y.length - xs.length));
    const tol = 5 * s * Math.sqrt(1 / pts.length + (t - (pts.length + 1) / 2) ** 2 / pts.reduce((a, [tt]) => a + (tt - (pts.length + 1) / 2) ** 2, 0)) + 1e-6;
    const okFit = m.kind === 'exp' ? Math.abs(Math.log(fit / item.truth)) <= tol : Math.abs(fit - item.truth) <= tol * (m.kind === 'seasonal' ? 2 : 1);
    const ok = Math.abs(direct - item.truth) < 1e-9 * Math.max(1, item.truth) && okFit && item.truth > 0;
    return { ok, detail: `model ${direct}, OLS ${fit}, item ${item.truth}, tol ${tol}` };
  },
  lesson: {
    purpose: 'A reported item shows a noisy time series, sometimes deliberately noisy, and asks for a future value. The trap is chasing the last noisy point.',
    anchor: 'Drawing a straight line through scattered points (a regression by eye), with one change: you then extend it beyond the data, where errors grow.',
    steps: [
      { say: 'Average a cluster of points at the start and at the end; the line through the two averages is your trend.', why: 'Averaging k points cuts noise by √k; the far-apart clusters pin the slope.' },
      { say: 'Extend the trend to the target time (for growth, use the doubling time).', why: 'The question asks for the noise-free model, not the next noisy observation.' },
      { say: 'Widen more the further you extrapolate.', why: 'Slope error multiplies with distance beyond the data.' },
    ],
    predict: { question: 'Data from t = 1 to 30 average 40 near t = 3 and 70 near t = 28. What is the trend at t = 40?', answer: 'Slope 30/25 = 1.2 per step, so 70 + 12 × 1.2 ≈ 84.' },
    rule: 'Trend from two averaged clusters; extrapolate; width grows with the distance beyond the data.',
    contrast: 'A noisy last point is not the trend. Extrapolating the last two points amplifies noise into the slope.',
    edge: 'For percentage growth, a straight-line extrapolation undershoots; use the doubling time (70 / growth%).',
  },
};

// Least squares by normal equations (tiny systems).
function ols(X, y) {
  const k = X[0].length;
  const A = Array.from({ length: k }, (_, i) => Array.from({ length: k }, (_, j) => X.reduce((s, r) => s + r[i] * r[j], 0)));
  const b = Array.from({ length: k }, (_, i) => X.reduce((s, r, n) => s + r[i] * y[n], 0));
  for (let c = 0; c < k; c++) {
    let p = c; for (let r = c + 1; r < k; r++) if (Math.abs(A[r][c]) > Math.abs(A[p][c])) p = r;
    [A[c], A[p]] = [A[p], A[c]]; [b[c], b[p]] = [b[p], b[c]];
    for (let r = 0; r < k; r++) if (r !== c) { const f = A[r][c] / A[c][c]; for (let j = c; j < k; j++) A[r][j] -= f * A[c][j]; b[r] -= f * b[c]; }
  }
  return b.map((v, i) => v / A[i][i]);
}

export default fam;
