// Curated Beat the Odds items modelled on reported past questions and classic sources.
// Every item is an original rewrite (never copied text), satisfies the item contract,
// carries meta.source (where the pattern was reported) and params (structured inputs).
import { makeRng } from '../../core/rng.js';
import { nCr, derangements, factorial } from '../../core/combinatorics.js';
import { Q } from '../../core/rational.js';
import { mcqItem, q, qpow, harmonic, Phi } from './lib.js';

const SRC = {
  prachub5: 'PracHub, "Optiver Beat The Odds: Five Rapid-Fire Probability Brainteasers (Dice, Cards, Coins, Pigeonhole)", https://prachub.com/interview-questions/optiver-beat-the-odds-five-rapid-fire-probability-brainteasers-dice-cards-coins-pigeonhole',
  prachubStats: 'PracHub, Optiver statistics and math question list (urn draws, octagon meeting walk, negative-price walk, unfair-coin bankroll), https://prachub.com/companies/optiver/categories/statistics-and-math',
  opa: '1Point3Acres topic list for the Optiver probability test (polygon walks, gambler\'s ruin, CLT estimates, optimal stopping), https://www.1point3acres.com/interview/problems/company/optiver/beat-the-odds-probability',
  programhelp: 'ProgramHelp, "Optiver OA experience" (two aces in a row), https://programhelp.net/en/oa/optiver-oa-experience-common-questions-and-how-to-prepare/',
  atp: 'Aptitude Test Prep, Optiver assessment overview (dice, cards and coins; closest-value options), https://aptitude-test-prep.com/employers/trading-assessments/optiver-assessment/',
  qbt: 'QuantBrainteasers, Optiver online assessment guide (die game expected value), https://quantbrainteasers.com/blog/optiver-online-assessment-mental-math-sequences-probability/',
  green: 'X. Zhou, A Practical Guide to Quantitative Finance Interviews ("Green Book"), 2008, probability and stochastic-process chapters',
  crack: 'T. F. Crack, Heard on the Street: Quantitative Questions from Wall Street Job Interviews',
  mosteller: 'F. Mosteller, Fifty Challenging Problems in Probability, 1965',
  classicDeMere: 'Chevalier de Méré problem (Pascal-Fermat correspondence, 1654)',
  pepys: 'Newton-Pepys problem (Samuel Pepys to Isaac Newton, 1693)',
  feller: 'W. Feller, An Introduction to Probability Theory and Its Applications, Vol. 1',
  monty: 'Monty Hall problem (Selvin 1975; vos Savant 1990)',
  tversky: 'Bar-Hillel and Falk (1982), "Some teasers concerning conditional probabilities"',
};

function mk(slug, family, difficulty, o, source) {
  const it = mcqItem(family, makeRng(`bank:${slug}`), difficulty, o);
  return { ...it, id: `bto-bank-${slug}`, meta: { source } };
}
const steps = (...pairs) => pairs.map(([say, why]) => ({ say, why }));

const bank = [
  mk('top-card-red', 'card-symmetry', 1, {
    value: q(1, 2),
    text: 'A shuffled 52-card deck has its top 10 cards removed and thrown away face down. What is the probability that the card now on top is red?',
    distractors: [
      { value: q(26, 42), misconception: 'Kept all 26 red cards but shrank the deck to 42. The unseen discards remove red and black cards alike.' },
      { value: q(16, 42), misconception: 'Assumed all 10 discards were red.' },
      { value: q(1, 4), misconception: 'Used the chance of one suit (1/4) instead of one colour.' },
      { value: 1 / 2 ** 11, misconception: 'Multiplied 1/2 for every card down to the 11th, as if all of them had to be red.' },
    ],
    steps: steps(['The 11th card of a shuffled deck is equally likely to be any of the 52 cards.', 'A fair shuffle treats every position alike.'], ['Discarding unseen cards gives no information, so P = 26/52 = 1/2.', 'Averaging over every possible discard returns the prior.']),
    rule: 'Unseen cards change nothing: any position of a shuffled deck is a uniform card.',
    anchor: 'The top card is red with probability 1/2; the 11th card is the same with a different position label.',
    hints: ['Did you learn anything about the discarded cards?', 'Position 11 is as random as position 1.'],
    params: { kind: 'discardRed', d: 10 },
  }, SRC.prachub5),
  mk('dice-11-or-12', 'two-dice-sum', 1, {
    value: q(3, 36),
    text: 'Two fair dice are thrown. What is the probability that their total is 11 or 12?',
    distractors: [
      { value: q(2, 11), misconception: 'Treated the 11 possible totals as equally likely.' },
      { value: q(2, 21), misconception: 'Counted unordered pairs {5,6} and {6,6} out of 21 as equally likely.' },
      { value: q(2, 36), misconception: 'Counted (5,6) once, forgetting (6,5).' },
      { value: q(1, 36), misconception: 'Only counted a total of 12.' },
    ],
    steps: steps(['Total 11: (5,6), (6,5). Total 12: (6,6). Three ordered pairs.', '36 equally likely ordered pairs.'], ['P = 3/36 = 1/12 ≈ 0.083.', 'Favourable over total.']),
    rule: 'Two dice: ways(s) = 6 − |s − 7| ordered pairs.',
    anchor: 'Counting favourable outcomes, with 36 ordered pairs instead of 6 faces.',
    hints: ['List the ordered pairs for 11 and for 12.', 'Remember (5,6) and (6,5) are different.'],
    params: { dice: 2, sides: 6, sums: [11, 12] },
  }, SRC.prachub5),
  mk('three-flips-same', 'coin-sequences', 1, {
    value: q(1, 4),
    text: 'A fair coin is flipped three times. What is the probability that all three flips land the same way?',
    distractors: [
      { value: q(1, 8), misconception: 'Only counted HHH; TTT also qualifies.' },
      { value: q(1, 2), misconception: 'Only compared the second flip with the first.' },
      { value: q(3, 4), misconception: 'Answered the complement.' },
      { value: q(3, 8), misconception: 'Counted one sequence per flip.' },
    ],
    steps: steps(['The first flip sets the side; the next two must match: (1/2)².', 'No particular side is required.'], ['P = 1/4 (HHH and TTT out of 8).', 'Two favourable sequences.']),
    rule: 'All n flips the same: (1/2)^(n−1).',
    anchor: 'One flip matches a given side with probability 1/2; repeated matches multiply.',
    hints: ['Is heads required?', 'Two flips must match the first.'],
    params: { kind: 'allSame', n: 3 },
  }, SRC.prachub5),
  mk('61-coins', 'pigeonhole', 1, {
    value: q(1),
    text: '61 coins are dropped at random into 15 boxes. You win if at least one box ends up holding more than 4 coins. What is the probability that you win?',
    distractors: [
      { value: 0, misconception: 'Thought an even spread keeps every box at 4 or fewer; 15 × 4 = 60 < 61.' },
      { value: 0.5, misconception: 'Treated overflow as a coin flip.' },
      { value: q(1, 15), misconception: 'Used the chance a coin lands in one given box.' },
      { value: 0.37, misconception: 'Estimated the chance for one particular box; the prize needs any box.' },
    ],
    steps: steps(['If no box had more than 4 coins, there would be at most 15 × 4 = 60 coins.', 'Add the caps.'], ['There are 61, so some box has at least 5 in every outcome: P = 1.', 'Pigeonhole principle.']),
    rule: 'n > k·m items in k boxes force a box above m.',
    anchor: 'Three socks from two colours force a pair; same idea with larger numbers.',
    hints: ['What is the most coins the boxes can hold without any exceeding 4?', 'Compare 60 with 61.'],
    params: { kind: 'coinsSure', n: 61, k: 15, m: 4 },
  }, SRC.prachub5),
  mk('second-throw-differs', 'die-repeats', 1, {
    value: q(5, 6),
    text: 'A die is thrown twice. What is the probability that the second throw differs from the first?',
    distractors: [
      { value: q(1, 6), misconception: 'Computed the chance that the throws match.' },
      { value: q(25, 36), misconception: 'Applied 5/6 to both throws; the first throw cannot clash with anything.' },
      { value: q(1, 2), misconception: 'Treated same/different as equally likely.' },
      { value: q(15, 36), misconception: 'Counted unordered pairs of different faces only once.' },
    ],
    steps: steps(['Whatever the first throw is, 5 of the 6 faces differ from it.', 'Condition on the first throw.'], ['P = 5/6.', 'The first throw is free.']),
    rule: 'P(second differs) = 1 − 1/6.',
    anchor: 'One throw has six equally likely faces; the second throw only needs to avoid one of them.',
    hints: ['Fix the first throw.', 'How many faces avoid it?'],
    params: { kind: 'allDiff', n: 2, k: 6 },
  }, SRC.prachub5),
  mk('hexagon-return', 'polygon-walk', 3, {
    ev: true, value: q(6),
    text: 'A bug sits on a corner of a regular hexagon. Every second it walks along an edge to one of the two adjacent corners, each with probability 1/2. On average, how many seconds until it is back at its starting corner?',
    distractors: [
      { value: 3, misconception: 'Assumed it goes halfway round and back.' },
      { value: 9, misconception: 'Used the time to reach the opposite corner.' },
      { value: 2, misconception: 'Only counted "out and straight back".' },
      { value: 36, misconception: 'Squared the number of corners.' },
    ],
    steps: steps(['In the long run the bug spends 1/6 of its time at each corner.', 'The symmetric walk has a uniform stationary distribution.'], ['Mean return time = 1/(1/6) = 6.', 'Return time is the reciprocal of long-run frequency.']),
    rule: 'Return time on an n-cycle = n.',
    anchor: 'Long-run frequency 1/6, turned into a waiting time by taking the reciprocal.',
    hints: ['How often is the bug at its start corner in the long run?', 'Mean return time = 1/frequency.'],
    params: { kind: 'return', n: 6 },
  }, SRC.opa),
  mk('hexagon-opposite', 'polygon-walk', 3, {
    ev: true, value: q(9),
    text: 'A token does a symmetric random walk on the corners of a regular hexagon, moving to a neighbouring corner each step. Starting at one corner, how many steps on average until it first reaches the opposite corner?',
    distractors: [
      { value: 3, misconception: 'Assumed it walks straight across.' },
      { value: 6, misconception: 'Used the return time.' },
      { value: 4.5, misconception: 'Halved 3 × 3, as if it always took the shorter side.' },
      { value: 12, misconception: 'Doubled the return time.' },
    ],
    steps: steps(['Unroll the hexagon at the target: walls 3 steps away on both sides.', 'Reaching the opposite corner from either side ends the walk.'], ['Exit time of a fair walk = product of the distances = 3 × 3 = 9.', 'Gambler\'s-ruin duration.']),
    rule: 'Hitting time on an n-cycle from distance k = k(n − k).',
    anchor: 'Gambler\'s-ruin duration a·b, on a line whose ends are glued together.',
    hints: ['Cut the hexagon open at the target.', 'Fair walk duration between walls at a and b is a·b.'],
    params: { kind: 'hit', n: 6, k: 3 },
  }, SRC.opa),
  mk('octagon-meet', 'polygon-walk', 5, {
    ev: true, value: q(8),
    text: 'Two tokens start on opposite corners of a regular octagon. Each second both move simultaneously and independently to a neighbouring corner, each direction with probability 1/2. On average, how many seconds until they occupy the same corner?',
    distractors: [
      { value: 4, misconception: 'Ignored the seconds when both move the same way and the gap does not change.' },
      { value: 16, misconception: 'Treated one token as fixed: a single walker from distance 4 on an octagon takes 4 × 4 = 16.' },
      { value: 2, misconception: 'Assumed they head straight for each other.' },
      { value: 6, misconception: 'Used the time from distance 2 instead of 4.' },
    ],
    steps: steps(['The gap changes by −2, 0, +2 with probabilities 1/4, 1/2, 1/4.', 'Toward, same way, apart.'], ['In units of 2 corners the gap is a lazy walk on a 4-cycle starting 2 away: non-lazy time 2 × 2 = 4.', 'Opposite corner of a square.'], ['The walk moves only half the time, so the expected time doubles: 8.', 'Laziness halves the speed.']),
    rule: 'Two walkers: study the gap; a lazy walk takes twice as long.',
    anchor: 'Single-walker hitting time k(n − k), applied to the gap.',
    hints: ['Track the distance between the tokens.', 'How does the gap change in one second?'],
    params: { kind: 'meet', n: 8, D: 4 },
  }, SRC.prachubStats),
  mk('two-aces', 'card-draws', 1, {
    value: q(1, 221),
    text: 'Two cards are dealt from a shuffled standard deck. What is the probability that both are aces?',
    distractors: [
      { value: q(1, 169), misconception: 'Used (4/52)², as if the first card were replaced.' },
      { value: q(8, 52), misconception: 'Added the two chances.' },
      { value: q(1, 13), misconception: 'Only computed the first card.' },
      { value: q(2, 221), misconception: 'Doubled for order; the sequential product already covers both orders.' },
    ],
    steps: steps(['P(first ace) = 4/52; P(second ace | first ace) = 3/51.', 'One ace and one card are gone.'], ['P = 4/52 × 3/51 = 1/221 ≈ 0.0045.', 'Chain rule.']),
    rule: 'Without replacement: multiply shrinking fractions.',
    anchor: 'One card: 4/52; the second draw repeats the fraction with both counts reduced.',
    hints: ['What is left after one ace is drawn?', '3 aces in 51 cards.'],
    params: { kind: 'twoAces' },
  }, SRC.programhelp),
  mk('two-reds-of-three', 'urn-draws', 2, {
    value: q(5, 7),
    text: 'A bag holds 5 red and 3 green counters. Three counters are drawn without replacement. What is the probability that at least two of them are red?',
    distractors: [
      { value: q(30, 56), misconception: 'Counted exactly two reds and forgot the all-red hands.' },
      { value: q(10, 56), misconception: 'Only counted three reds.' },
      { value: new Q(nCr(3, 2) * 25n * 3n + 125n, 512n), misconception: 'Treated the draws as with replacement (binomial with p = 5/8).' },
      { value: q(2, 7), misconception: 'Answered the complement.' },
    ],
    steps: steps(['Total hands: C(8,3) = 56.', 'Equally likely 3-subsets.'], ['Two reds: C(5,2)·C(3,1) = 30; three reds: C(5,3) = 10.', 'Choose the reds and the greens.'], ['P = 40/56 = 5/7 ≈ 0.714.', 'Favourable over total.']),
    rule: 'Hypergeometric: C(r,j)C(b,k−j)/C(n,k), summed for "at least".',
    anchor: 'The binomial count, with draws that do not go back.',
    hints: ['Count 3-subsets.', 'Split into exactly two reds and three reds.'],
    params: { r: 5, b: 3, k: 3, j: 2, atLeast: true },
  }, SRC.prachubStats),
  mk('bankroll-unfair', 'gamblers-ruin', 4, {
    value: q(1).sub(qpow(q(11, 9), 10)).div(q(1).sub(qpow(q(11, 9), 20))),
    text: 'You start with $10 and repeatedly bet $1 on a game you win with probability 0.45. You stop when you reach $20 or lose everything. What is the probability that you reach $20?',
    distractors: [
      { value: 0.5, misconception: 'Used the fair-game answer 10/20, ignoring the 5-point edge against you.' },
      { value: 0.45, misconception: 'Used the one-bet probability for the whole game.' },
      { value: q(1).sub(qpow(q(9, 11), 10)).div(q(1).sub(qpow(q(9, 11), 20))), misconception: 'Used p/q instead of q/p: that is the answer with the edge in your favour.' },
      { value: Math.pow(0.45, 10), misconception: 'Required ten wins in a row.' },
    ],
    steps: steps(['r = q/p = 0.55/0.45 = 11/9.', 'Ratio of down to up probabilities.'], ['P = (1 − r^10)/(1 − r^20) ≈ 0.119.', 'Biased gambler\'s ruin.']),
    rule: 'Biased ruin: (1 − r^i)/(1 − r^N), r = q/p.',
    anchor: 'Fair ruin i/N, with r^wealth replacing wealth as the fair quantity.',
    hints: ['Compute r = q/p.', 'Plug into (1 − r^i)/(1 − r^N).'],
    params: { mode: 'biased', i: 10, N: 20, a: 9, c: 20 },
  }, SRC.prachubStats),
  mk('price-negative', 'random-walk-line', 3, {
    value: q(37, 256),
    text: 'A price starts at 2 and each day moves up or down by 1 with equal probability (it may go negative). What is the probability that it is below 0 after 8 days?',
    distractors: [
      { value: q(93, 256), misconception: 'Counted a price of exactly 0 as below 0.' },
      { value: 0.5, misconception: 'Treated above/below zero as a coin flip, ignoring the starting cushion of 2.' },
      { value: q(219, 256), misconception: 'Answered the complement.' },
      { value: q(74, 256), misconception: 'Applied the reflection doubling, which is for "ever below 0", not "below 0 at the end".' },
    ],
    steps: steps(['Price = 2 + S_8, and S_8 is even after 8 steps, so "below 0" means S_8 ≤ −4.', 'Parity: S_8 ∈ {−8, −6, …, 8}.'], ['S_8 = 2u − 8 ≤ −4 ⇔ at most 2 up-days: C(8,0) + C(8,1) + C(8,2) = 1 + 8 + 28 = 37.', 'Choose which days go up.'], ['P = 37/256 ≈ 0.145.', 'Divide by 2^8 paths.']),
    rule: 'Terminal price events are binomial tails; mind parity and strict inequalities.',
    anchor: 'Heads in 8 flips, relabelled as a price path.',
    hints: ['After 8 days the move is even.', 'Translate into a number of up-days.'],
    params: { kind: 'below', n: 8, start: 2 },
  }, SRC.prachubStats),
];

// Remaining items use a compact spec: [slug, family, difficulty, source, spec].
const more = [
  ['demere-four-throws', 'at-least-one', 2, SRC.classicDeMere, {
    value: q(1).sub(qpow(q(5, 6), 4)),
    text: 'You throw a die four times. What is the probability of at least one six?',
    distractors: [
      { value: q(4, 6), misconception: 'Added 1/6 four times; the events overlap.' },
      { value: qpow(q(5, 6), 4), misconception: 'Answered the complement.' },
      { value: q(4, 6).mul(qpow(q(5, 6), 3)), misconception: 'Computed exactly one six.' },
      { value: q(1, 2), misconception: 'Guessed an even chance.' },
    ],
    steps: steps(['P(no six) = (5/6)^4 = 625/1296.', 'Independent misses multiply.'], ['P = 1 − 625/1296 = 671/1296 ≈ 0.518.', 'Complement.']),
    rule: 'At least one = 1 − P(none).', anchor: 'The complement rule with "none" as a product.',
    hints: ['Complement: no six at all.', '(5/6)^4.'], params: { variant: 'six', ps: [[1, 6], [1, 6], [1, 6], [1, 6]] },
  }],
  ['demere-double-six', 'at-least-one', 3, SRC.classicDeMere, {
    value: q(1).sub(qpow(q(35, 36), 24)),
    text: 'You throw a pair of dice 24 times. What is the probability of at least one double six?',
    distractors: [
      { value: q(24, 36), misconception: 'Added 1/36 twenty-four times; overlapping events double count.' },
      { value: qpow(q(35, 36), 24), misconception: 'Answered the complement.' },
      { value: q(1).sub(qpow(q(5, 6), 24)), misconception: 'Used 5/6 per throw, the chance one die is not a six.' },
      { value: q(1, 2), misconception: 'Assumed de Méré\'s bet is exactly fair.' },
    ],
    steps: steps(['P(no double six in one throw) = 35/36.', 'Only (6,6) of 36 outcomes.'], ['P = 1 − (35/36)^24 ≈ 0.491.', 'Just below one half, which is why de Méré lost money.']),
    rule: '1 − (35/36)^n; the break-even n is 25.', anchor: 'Four-throw version with 1/36 in place of 1/6.',
    hints: ['Complement.', '(35/36)^24.'], params: { variant: 'demere', ps: Array(24).fill([1, 36]) },
  }],
  ['pepys-six-dice', 'at-least-one', 2, SRC.pepys, {
    value: q(1).sub(qpow(q(5, 6), 6)),
    text: 'Six fair dice are thrown. What is the probability that at least one shows a six?',
    distractors: [
      { value: 1, misconception: 'Added 1/6 six times and got 1: you can miss on every die.' },
      { value: qpow(q(5, 6), 6), misconception: 'Answered the complement.' },
      { value: 1 - Math.exp(-1), misconception: 'Used the large-n limit 1 − 1/e ≈ 0.632 instead of the exact 6-die value.' },
      { value: q(1, 2), misconception: 'Guessed one half.' },
    ],
    steps: steps(['P(no six) = (5/6)^6 ≈ 0.335.', 'Independent dice.'], ['P ≈ 0.665.', 'Complement.']),
    rule: 'At least one = 1 − (1 − p)^n.', anchor: 'The four-throw de Méré bet with six dice.',
    hints: ['Complement.', '(5/6)^6 ≈ 1/3.'], params: { variant: 'six', ps: Array(6).fill([1, 6]) },
  }],
  ['birthday-23', 'birthday', 3, SRC.feller, {
    value: q(1).sub(new Q((() => { let p = 1n; for (let i = 0n; i < 23n; i++) p *= 365n - i; return p; })(), 365n ** 23n)),
    text: '23 people are in a room. Ignoring leap years and assuming all 365 birthdays equally likely, what is the probability that at least two share a birthday?',
    distractors: [
      { value: q(23, 365), misconception: 'Scaled one person\'s chance by 23; collisions come from 253 pairs.' },
      { value: q(1).sub(qpow(q(364, 365), 22)), misconception: 'Only checked matches with one particular person.' },
      { value: 0.25, misconception: 'Guessed that 23 of 365 days makes a match unlikely.' },
      { value: 0.9, misconception: 'Overshot: 23 people give only just over one half.' },
    ],
    steps: steps(['P(all different) = 365·364·…·343 / 365^23 ≈ 0.493.', 'Each new person avoids all earlier birthdays.'], ['P ≈ 0.507.', 'Complement.']),
    rule: 'P(collision) ≈ 1 − e^(−n(n−1)/730).', anchor: 'All-different dice with 365 faces.',
    hints: ['Complement: all different.', '253 pairs, each matching with chance 1/365.'], params: { mode: 'any', d: 365, n: 23 },
  }],
  ['monty-three', 'monty-hall', 2, SRC.monty, {
    value: q(2, 3),
    text: 'Three doors hide one car and two goats. You pick door 1; the host, who knows where the car is, opens a different door showing a goat and lets you switch. If you switch, what is your chance of winning the car?',
    distractors: [
      { value: q(1, 2), misconception: 'Treated the two closed doors as equally likely; the host\'s knowledge breaks the symmetry.' },
      { value: q(1, 3), misconception: 'Answered the staying probability.' },
      { value: 1, misconception: 'Believed switching always wins.' },
      { value: q(1, 4), misconception: 'Multiplied 1/2 by 1/2 for no reason.' },
    ],
    steps: steps(['Your door keeps 1/3: the host can always show a goat.', 'His action says nothing about your door.'], ['The other closed door gets the remaining 2/3.', 'He never opens the car.']),
    rule: 'Knowing host: switch wins (n − 1)/n with 3 doors → 2/3.', anchor: 'Bayes updating where the evidence depends on the host\'s rule.',
    hints: ['Could the host have shown the car?', 'Your door\'s probability does not move.'], params: { n: 3, m: 1, variant: 'switch' },
  }],
  ['five-letters', 'derangements', 2, SRC.mosteller, {
    value: new Q(derangements(5), factorial(5)),
    text: 'Five letters are placed at random into five addressed envelopes. What is the probability that no letter is in its correct envelope?',
    distractors: [
      { value: qpow(q(4, 5), 5), misconception: 'Treated each letter as missing independently with chance 4/5.' },
      { value: q(1).sub(new Q(derangements(5), factorial(5))), misconception: 'Answered "at least one correct".' },
      { value: q(4, 5), misconception: 'Only looked at one letter.' },
      { value: q(1, 120), misconception: 'Counted one arrangement.' },
    ],
    steps: steps(['Derangements: D(5) = 44.', 'D(n) = (n − 1)(D(n−1) + D(n−2)) with D(3) = 2, D(4) = 9.'], ['P = 44/120 = 11/30 ≈ 0.367 (almost exactly 1/e).', 'All 120 arrangements are equally likely.']),
    rule: 'D(n)/n! ≈ 1/e.', anchor: 'At-least-one by complement, with dependent matches.',
    hints: ['Count arrangements with no letter in place.', 'D(5) = 44.'], params: { kind: 'none', n: 5 },
  }],
  ['first-six-mean', 'expected-waiting', 1, SRC.qbt, {
    ev: true, value: q(6),
    text: 'You throw a die until a six appears. What is the expected number of throws, counting the six?',
    distractors: [
      { value: 5, misconception: 'Counted only the failed throws.' },
      { value: 3.5, misconception: 'Averaged the face values.' },
      { value: 4, misconception: 'Answered the median wait.' },
      { value: 36, misconception: 'Squared 6.' },
    ],
    steps: steps(['E = 1 + (5/6)E.', 'After a miss you are back at the start.'], ['E = 6.', 'Geometric wait 1/p.']),
    rule: 'Geometric wait = 1/p.', anchor: 'The frequency 1/6 turned into a waiting time.',
    hints: ['Set up E = 1 + (5/6)E.', 'Solve.'], params: { kind: 'first', a: 1, c: 6 },
  }],
  ['double-six-wait', 'expected-waiting', 3, SRC.green, {
    ev: true, value: q(42),
    text: 'A die is thrown until two consecutive sixes appear. What is the expected number of throws?',
    distractors: [
      { value: 36, misconception: 'Treated each pair of throws as an independent 1/36 attempt.' },
      { value: 72, misconception: 'Used non-overlapping blocks of two.' },
      { value: 12, misconception: 'Added two waits of 6, ignoring resets.' },
      { value: 7, misconception: 'Waited for any repeated face.' },
    ],
    steps: steps(['E0 = 1 + (5/6)E0 + (1/6)E1; E1 = 1 + (5/6)E0.', 'State 1 means the last throw was a six.'], ['Solve: E0 = 42.', 'Two linear equations.']),
    rule: 'Two sixes in a row: 6² + 6 = 42.', anchor: 'Waiting for one six (6), with progress that can be lost.',
    hints: ['Track "last throw was a six".', 'Solve two equations.'], params: { kind: 'doubleSix', s: 6 },
  }],
  ['hh-wait', 'pattern-waiting', 3, SRC.green, {
    ev: true, value: q(6),
    text: 'A fair coin is flipped until two heads in a row appear. What is the expected number of flips?',
    distractors: [
      { value: 4, misconception: 'Used the answer for HT: after a failed HH attempt you lose your progress.' },
      { value: 8, misconception: 'Doubled 2².' },
      { value: 3, misconception: 'Thought a head then another head takes 1.5 flips each.' },
      { value: 2, misconception: 'Assumed two flips suffice.' },
    ],
    steps: steps(['HH overlaps itself at lengths 1 and 2.', 'The last H of a failed attempt could start a new one only if it is an H.'], ['E = 2 + 4 = 6.', 'Sum of 2^k over self-overlaps.']),
    rule: 'Pattern wait = Σ 2^k over self-overlaps.', anchor: 'Waiting for one head (2 flips), with overlaps deciding what survives a near miss.',
    hints: ['Does HH overlap itself?', 'Add 2^k for each overlap.'], params: { mode: 'wait', A: 'HH' },
  }],
  ['penney-hh-th', 'pattern-waiting', 4, SRC.green, {
    value: q(3, 4),
    text: 'A fair coin is flipped until either HH or TH appears. What is the probability that TH comes first?',
    distractors: [
      { value: q(1, 2), misconception: 'Assumed equal-length patterns are equally likely to win.' },
      { value: q(1, 4), misconception: 'Answered P(HH first).' },
      { value: q(2, 3), misconception: 'Used the waiting-time odds 6 : 4 (as HH : TH).' },
      { value: q(7, 8), misconception: 'Guessed a big edge without computing it.' },
    ],
    steps: steps(['HH wins only if the first two flips are HH.', 'Any T before that sets up TH before HH can complete.'], ['P(TH first) = 1 − 1/4 = 3/4.', 'Complement.']),
    rule: 'A pattern whose prefix is the rival\'s suffix steals progress.', anchor: 'Waiting times, with two patterns racing.',
    hints: ['When can HH still win?', 'Only on flips 1–2.'], params: { mode: 'race', A: 'TH', B: 'HH' },
  }],
  ['all-faces', 'coupon-collector', 2, SRC.green, {
    ev: true, value: q(6).mul(harmonic(6)),
    text: 'A die is thrown until every face has appeared at least once. What is the expected number of throws?',
    distractors: [
      { value: 6, misconception: 'Assumed each throw shows a new face.' },
      { value: 21, misconception: 'Added 1 + 2 + … + 6.' },
      { value: 36, misconception: 'Squared 6.' },
      { value: 6 * Math.log(6), misconception: 'Used 6 ln 6 ≈ 10.75, dropping the 0.577·6 term.' },
    ],
    steps: steps(['Stages: 6/6 + 6/5 + 6/4 + 6/3 + 6/2 + 6/1.', 'With i faces missing, a new face comes with probability i/6.'], ['Total = 14.7.', 'Linearity.']),
    rule: 'n·H_n.', anchor: 'Geometric waits stacked with shrinking p.',
    hints: ['Split into stages.', 'Stage waits 6/i.'], params: { s: 6, k: 6 },
  }],
  ['reroll-once', 'dice-games-ev', 3, SRC.crack, {
    ev: true, value: q(17, 4), minGap: (c) => Math.max(0.05, Math.abs(c) * 0.015),
    text: 'You roll a die and are paid its face in dollars, but you may reroll once and must then accept the second roll. With the best strategy, what is the game worth?',
    distractors: [
      { value: 3.5, misconception: 'Ignored the reroll option.' },
      { value: q(161, 36), misconception: 'Used the maximum of two rolls; a reroll must be accepted.' },
      { value: q(25, 6), misconception: 'Rerolled a 4, which beats the 3.5 you expect from rerolling.' },
      { value: 5, misconception: 'Assumed the reroll lifts the value to the top half average.' },
    ],
    steps: steps(['Reroll is worth 3.5, so keep 4, 5, 6 and reroll 1, 2, 3.', 'Compare the sure face with 3.5.'], ['Value = (4 + 5 + 6)/6 + (3/6)(3.5) = 2.5 + 1.75 = 4.25.', 'Average over the first roll.']),
    rule: 'V2 = E[max(X, 3.5)] = 4.25.', anchor: 'The average roll, with the option to discard low rolls.',
    hints: ['What is a reroll worth?', 'Keep rolls above that.'], params: { kind: 'reroll', k: 6, rolls: 2 },
  }],
  ['reroll-twice', 'dice-games-ev', 4, SRC.crack, {
    ev: true, value: q(14, 3), minGap: (c) => Math.max(0.05, Math.abs(c) * 0.015),
    text: 'You roll a die, paid its face in dollars, and may reroll up to two times, keeping only the last roll. With optimal play, what is the game worth?',
    distractors: [
      { value: 4.25, misconception: 'Used the one-reroll value.' },
      { value: 3.5, misconception: 'Ignored the rerolls.' },
      { value: q(119, 24), misconception: 'Used the maximum of three rolls, as if you could go back.' },
      { value: 5, misconception: 'Kept only sixes and fives on the first roll and guessed the rest.' },
    ],
    steps: steps(['With one reroll left the game is worth 4.25, so on the first roll keep 5 and 6.', 'Keep iff the face beats 4.25.'], ['Value = (5 + 6)/6 + (4/6)(4.25) = 11/6 + 17/6 = 14/3 ≈ 4.667.', 'Average over the first roll.']),
    rule: 'Backward induction: 3.5 → 4.25 → 4.667.', anchor: 'The one-reroll game, one level deeper.',
    hints: ['Solve the last decision first.', 'Keep a roll iff it beats 4.25.'], params: { kind: 'threeRolls', k: 6, rolls: 3 },
  }],
  ['red-black-small', 'card-stopping', 4, SRC.green, {
    ev: true, value: q(2, 3), minGap: (c) => Math.max(0.05, Math.abs(c) * 0.06),
    text: 'Two red and two black cards are shuffled and turned over one at a time. Each red pays $1, each black costs $1, and you may stop whenever you like. With the best strategy, what is this game worth?',
    distractors: [
      { value: 0, misconception: 'Played the whole deck: a balanced deck is worth 0 only without the option to stop.' },
      { value: q(1, 2), misconception: 'Used the one-red-one-black value.' },
      { value: 1, misconception: 'Assumed you can always stop one card ahead.' },
      { value: q(1, 3), misconception: 'Halved the option value by guesswork.' },
    ],
    steps: steps(['V(1,1) = 1/2, V(2,1) = 4/3, V(1,2) = 0.', 'Solve small decks first.'], ['V(2,2) = ½(1 + 0) + ½(−1 + 4/3) = 2/3.', 'Draw once and continue optimally.']),
    rule: 'V(r,b) = max(0, draw value).', anchor: 'The reroll rule on a deck that changes as you draw.',
    hints: ['Start with one red and one black.', 'Build V(2,1) and V(1,2).'], params: { r: 2, b: 2 },
  }],
  ['broken-stick', 'uniform-geometry', 3, SRC.green, {
    value: q(1, 4),
    text: 'A stick is broken at two points chosen independently and uniformly along it. What is the probability that the three pieces form a triangle?',
    distractors: [
      { value: q(1, 2), misconception: 'Guessed half.' },
      { value: q(3, 4), misconception: 'Answered the complement.' },
      { value: q(1, 8), misconception: 'Multiplied three "piece < 1/2" chances as if independent.' },
      { value: q(1, 3), misconception: 'Thought one of the three pieces is too long a third of the time.' },
    ],
    steps: steps(['Triangle ⇔ every piece < 1/2.', 'Triangle inequality.'], ['Each piece is ≥ 1/2 with probability 1/4, and at most one can be; so P(triangle) = 1 − 3/4 = 1/4.', 'Disjoint bad events.']),
    rule: 'Broken stick triangle: 1/4.', anchor: 'Lengths on a line become areas in a square.',
    hints: ['When do three lengths make a triangle?', 'No piece may reach half the stick.'], params: { kind: 'triangle' },
  }],
  ['meet-15', 'uniform-geometry', 3, SRC.feller, {
    value: q(7, 16),
    text: 'Two traders each arrive at a random time between 9:00 and 10:00, independently. Each waits 15 minutes for the other and then leaves. What is the probability that they meet?',
    distractors: [
      { value: q(1, 4), misconception: 'Only one trader waits.' },
      { value: q(1, 2), misconception: 'Added both windows without removing the overlap outside the hour.' },
      { value: q(9, 16), misconception: 'Answered the complement.' },
      { value: q(1, 16), misconception: 'Squared the waiting fraction.' },
    ],
    steps: steps(['Meet ⇔ |x − y| ≤ 15 in a 60 × 60 square.', 'Uniform point in the square.'], ['Miss area = two triangles with legs 45: (3/4)² of the square. P = 1 − 9/16 = 7/16.', 'Area of the band.']),
    rule: '1 − (1 − w)².', anchor: 'Interval length on a line, lifted to area in a square.',
    hints: ['Draw the square of arrival times.', 'The miss region is two corner triangles.'], params: { kind: 'meet', w: 15 },
  }],
  ['max-two-dice', 'expected-extremes', 2, SRC.green, {
    ev: true, value: q(161, 36), minGap: (c) => Math.max(0.05, Math.abs(c) * 0.02),
    text: 'Two dice are thrown. What is the expected value of the larger face?',
    distractors: [
      { value: 3.5, misconception: 'Used one die\'s average.' },
      { value: 4, misconception: 'Used the continuous formula 6·2/3.' },
      { value: q(91, 36), misconception: 'Computed the expected smaller face.' },
      { value: 5, misconception: 'Assumed the larger face is usually 5 or 6.' },
    ],
    steps: steps(['E[max] = Σ_k P(max ≥ k) = Σ (1 − ((k−1)/6)²).', 'Tail-sum formula.'], ['= 1 + 35/36 + 32/36 + 27/36 + 20/36 + 11/36 = 161/36 ≈ 4.47.', 'Add the six terms.']),
    rule: 'E[max of two dice] = 161/36.', anchor: 'P(max ≤ k) = (k/6)², summed as tails.',
    hints: ['Use E[X] = Σ P(X ≥ k).', 'P(max ≥ k) = 1 − ((k−1)/6)².'], params: { mode: 'dice', n: 2, s: 6, minOf: false },
  }],
  ['rare-disease', 'bayes-test', 3, SRC.feller, {
    value: q(1, 2),
    text: '1% of a population has a condition. A test is positive for 99% of people with it and for 1% of people without it. A random person tests positive. What is the probability that they have the condition?',
    distractors: [
      { value: 0.99, misconception: 'Base-rate neglect: used P(positive | condition).' },
      { value: 0.01, misconception: 'Ignored the test result.' },
      { value: 0.0099, misconception: 'Computed P(condition and positive) without dividing.' },
      { value: 0.0198, misconception: 'Computed P(positive).' },
    ],
    steps: steps(['True positives: 0.01 × 0.99 = 0.0099; false positives: 0.99 × 0.01 = 0.0099.', 'Split positives by source.'], ['P = 0.0099/0.0198 = 1/2.', 'Fraction of positives that are real.']),
    rule: 'Posterior = true positives / all positives.', anchor: 'P(A | B) = P(A and B)/P(B).',
    hints: ['Imagine 10,000 people.', 'Compare true and false positives.'], params: { pv: [1, 100], sv: [99, 100], fv: [1, 100], variant: 'pos' },
  }],
  ['two-children', 'conditional-dice', 2, SRC.tversky, {
    value: q(1, 3),
    text: 'A family has two children, at least one of whom is a girl. Each child is independently a girl with probability 1/2. What is the probability that both are girls?',
    distractors: [
      { value: q(1, 2), misconception: 'Treated "the other child" as a single uncertain child; the information does not say which child.' },
      { value: q(1, 4), misconception: 'Ignored the information.' },
      { value: q(2, 3), misconception: 'Computed one girl and one boy.' },
      { value: q(3, 4), misconception: 'Computed P(at least one girl).' },
    ],
    steps: steps(['Outcomes GG, GB, BG, BB; the information removes BB.', 'Ordered pairs of children.'], ['P(GG | at least one G) = 1/3.', 'Three equally likely outcomes remain.']),
    rule: 'Condition by deleting outcomes, then count.', anchor: 'Favourable over total with a smaller total.',
    hints: ['List four ordered outcomes.', 'Delete BB.'], params: { kids: true, older: false },
  }],
  ['three-cards', 'bayes-boxes', 2, SRC.feller, {
    value: q(2, 3),
    text: 'One card is red on both sides, one is black on both sides, and one is red on one side and black on the other. A card is drawn at random and a random side is shown: it is red. What is the probability that the hidden side is red?',
    distractors: [
      { value: q(1, 2), misconception: 'Counted cards with a red side (two) as equally likely; count red faces instead.' },
      { value: q(1, 3), misconception: 'Used the prior chance of the red-red card.' },
      { value: q(1, 4), misconception: 'Multiplied 1/2 × 1/2.' },
      { value: q(3, 4), misconception: 'Guessed high without counting.' },
    ],
    steps: steps(['Three red faces could be showing: two on the red-red card, one on the mixed card.', 'Faces are equally likely.'], ['Two of the three have a red back: P = 2/3.', 'Condition on the seen face.']),
    rule: 'Count the equally likely things you could have seen.', anchor: 'Bayes with counts of faces.',
    hints: ['How many red faces are there?', 'Which of them have red backs?'], params: { kind: 'cards', rr: 1, mx: 1, bb: 1 },
  }],
  ['double-headed', 'bayes-boxes', 3, SRC.crack, {
    value: q(8, 17),
    text: 'A jar holds 10 coins: 9 fair and 1 double-headed. You pick one at random, flip it three times, and see three heads. What is the probability it is the double-headed coin?',
    distractors: [
      { value: q(1, 10), misconception: 'Ignored the flips.' },
      { value: q(7, 8), misconception: 'Used 1 − 1/8, ignoring that fair coins are nine times as common.' },
      { value: q(4, 13), misconception: 'Used two heads instead of three.' },
      { value: q(8, 18), misconception: 'Counted 10 fair coins instead of 9.' },
    ],
    steps: steps(['Prior odds 1 : 9; likelihood of HHH 1 : 1/8.', 'Double-headed always shows heads.'], ['Posterior odds 1 : 9/8 = 8 : 9, so P = 8/17 ≈ 0.47.', 'Odds form of Bayes.']),
    rule: 'Posterior odds = prior odds × likelihood ratio.', anchor: 'Bayes for a test, where the test is the flips.',
    hints: ['Write prior odds.', 'Multiply by the likelihood ratio 8.'], params: { kind: 'coins', m: 10, k: 3 },
  }],
  ['hat-check-mean', 'linearity', 2, SRC.feller, {
    ev: true, value: q(1), minGap: (c) => Math.max(0.04, Math.abs(c) * 0.05),
    text: 'Twenty people check their coats and get them back in a random order. What is the expected number of people who receive their own coat?',
    distractors: [
      { value: q(1, 20), misconception: 'Gave the probability for one person.' },
      { value: 10, misconception: 'Assumed about half.' },
      { value: 0, misconception: 'Thought dependence cancels the matches.' },
      { value: 20 * Math.exp(-1), misconception: 'Multiplied by 1/e, the probability of no match at all.' },
    ],
    steps: steps(['Indicator per person, each with probability 1/20.', 'Their coat is uniformly placed.'], ['Expected count = 20 × 1/20 = 1.', 'Linearity.']),
    rule: 'Expected fixed points = 1.', anchor: 'E of a sum = sum of E.',
    hints: ['Write the count as a sum of indicators.', 'Each has probability 1/20.'], params: { kind: 'fixed', n: 20 },
  }],
  ['running-total-6', 'running-sum', 3, SRC.opa, {
    value: q(16807, 46656),
    text: 'You throw a die repeatedly and keep a running total. What is the probability that the total is exactly 6 at some point?',
    distractors: [
      { value: q(1, 6), misconception: 'Only counted a first throw of 6.' },
      { value: q(2, 7), misconception: 'Used the long-run limit 2/7; small totals are hit more often.' },
      { value: 0.5, misconception: 'Treated hit or skip as a coin flip.' },
      { value: q(29849, 46656), misconception: 'Answered P(skip over 6).' },
    ],
    steps: steps(['p(n) = (1/6)[p(n−1) + … + p(n−6)], p(0) = 1.', 'Condition on the last throw.'], ['For n ≤ 6 this gives p(n) = (7/6)^(n−1)/6, so p(6) = 7^5/6^6 ≈ 0.360.', 'Iterate.']),
    rule: 'p(n) averages the previous six; limit 2/7.', anchor: 'Stair-climbing counts weighted by probability.',
    hints: ['How can the total land on 6?', 'Average the previous values.'], params: { mode: 'hit', n: 6, steps: [1, 2, 3, 4, 5, 6] },
  }],
  ['series-seven-games', 'race-to-k', 2, SRC.crack, {
    value: q(5, 16),
    text: 'Two equally strong teams play a best-of-seven series. What is the probability that it goes to a seventh game?',
    distractors: [
      { value: q(1, 64), misconception: 'Counted one alternating win pattern.' },
      { value: q(1, 4), misconception: 'Treated the four possible series lengths as equally likely.' },
      { value: q(11, 16), misconception: 'Answered the complement.' },
      { value: q(1, 2), misconception: 'Treated it as a coin flip.' },
    ],
    steps: steps(['Game 7 happens ⇔ the first six games split 3–3.', 'Otherwise someone has 4 wins.'], ['P = C(6,3)/2^6 = 20/64 = 5/16.', 'Binomial count.']),
    rule: 'Full length: C(2k−2, k−1)/2^(2k−2).', anchor: 'Exactly 3 heads in 6 flips.',
    hints: ['What must the score be after six games?', 'C(6,3)/64.'], params: { mode: 'full', k: 4, a: 1, c: 2 },
  }],
  ['sixty-heads', 'clt-estimates', 3, SRC.opa, {
    value: (() => { let s = 0n, c = 1n; for (let k = 0; k <= 100; k++) { if (k >= 60) s += c; c = (c * BigInt(100 - k)) / BigInt(k + 1); } return new Q(s, 2n ** 100n); })(),
    text: 'A fair coin is flipped 100 times. Roughly what is the probability of at least 60 heads?',
    distractors: [
      { value: 1 - Phi(10 / 25), misconception: 'Divided by the variance 25 instead of the sd 5.' },
      { value: 1 - Phi(1), misconception: 'Used √100 = 10 as the sd.' },
      { value: 0.057, misconception: 'Counted both tails.' },
      { value: 0.5 - 0.0284, misconception: 'Read the table as the area between the mean and z.' },
    ],
    steps: steps(['Mean 50, sd √100/2 = 5; 60 is 2 sd above the mean.', 'Binomial(100, 1/2).'], ['Continuity-corrected z = 1.9 → about 2.9%; exact 2.84%.', 'Normal tail landmark 2.3% at 2 sd.']),
    rule: 'sd of heads in n flips = √n/2.', anchor: 'The 68-95-99.7 rule applied to a sum.',
    hints: ['sd = 5.', 'How many sd is 60?'], params: { kind: 'coinTail', n: 100, lo: 60, hi: 100 },
  }],
  ['socks-three-colours', 'pigeonhole', 1, SRC.atp, {
    value: q(1),
    text: 'A drawer holds 10 socks of each of three colours. In the dark you take four socks. What is the probability that you have at least two of the same colour?',
    distractors: [
      { value: q(2, 3), misconception: 'Estimated a likely-but-uncertain chance; four socks in three colours force a match.' },
      { value: q(1, 3), misconception: 'Used the chance two particular socks match.' },
      { value: 0.5, misconception: 'Coin flip.' },
      { value: q(153, 203), misconception: 'Used the three-sock answer, 1 − (30·20·10)/(30·29·28); the fourth sock removes all doubt.' },
    ],
    steps: steps(['At most three socks can all have different colours.', 'One per colour.'], ['A fourth sock must repeat a colour: P = 1.', 'Pigeonhole.']),
    rule: 'More items than categories → a repeat is certain.', anchor: 'Coins into boxes, with colours as boxes.',
    hints: ['Compare socks with colours.', '4 > 3.'], params: { kind: 'socksSure', c: 3, s: 10, d: 4 },
  }],
  ['pair-two-cards', 'card-draws', 1, SRC.atp, {
    value: q(3, 51),
    text: 'Two cards are drawn from a shuffled deck. What is the probability that they have the same rank?',
    distractors: [
      { value: q(1, 13), misconception: 'Drew with replacement.' },
      { value: q(4, 51), misconception: 'Left four of the rank in the deck.' },
      { value: q(12, 51), misconception: 'Computed same suit.' },
      { value: q(1, 221), misconception: 'Required a specific rank.' },
    ],
    steps: steps(['The first card fixes the rank.', 'Any rank works.'], ['Three of that rank remain among 51: P = 3/51 = 1/17.', 'Without replacement.']),
    rule: 'Pair in two cards: 3/51.', anchor: 'One draw with shrinking counts.',
    hints: ['Fix the first card.', 'How many of its rank remain?'], params: { kind: 'pair' },
  }],
  ['higher-die', 'dice-duel', 2, SRC.atp, {
    value: q(15, 36),
    text: 'You and an opponent each throw one die; you win only with a strictly higher number. What is your chance of winning?',
    distractors: [
      { value: q(1, 2), misconception: 'Ignored ties.' },
      { value: q(21, 36), misconception: 'Counted ties as wins.' },
      { value: q(1, 6), misconception: 'Computed the tie probability.' },
      { value: q(5, 6), misconception: 'Counted every non-tie as a win.' },
    ],
    steps: steps(['P(tie) = 1/6.', 'Six doubles.'], ['The other 30 outcomes split evenly: P = 15/36 = 5/12.', 'Symmetry.']),
    rule: '(1 − P(tie))/2.', anchor: '36 ordered pairs compared instead of added.',
    hints: ['Remove ties first.', 'Split the rest in half.'], params: { A: { type: 'die', k: 6 }, B: { type: 'die', k: 6 }, reroll: false },
  }],
  ['three-dice-ten', 'three-dice', 3, SRC.atp, {
    value: q(27, 216),
    text: 'Three dice are thrown. What is the probability that the total is 10?',
    distractors: [
      { value: q(1, 16), misconception: 'Treated the 16 totals as equally likely.' },
      { value: q(6, 56), misconception: 'Counted unordered combinations as equally likely.' },
      { value: q(6, 216), misconception: 'Counted each combination once.' },
      { value: q(27, 36), misconception: 'Divided by 36.' },
    ],
    steps: steps(['Ordered triples with total 10: 27 (the peak of the distribution, shared with 11).', 'Fix the first two dice; the third is determined.'], ['P = 27/216 = 1/8.', 'Favourable over total.']),
    rule: 'Three dice: totals 10 and 11 each have 27 ways.', anchor: 'Two-dice sums with one more die.',
    hints: ['Count ordered triples.', 'Fix two dice at a time.'], params: { kind: 'sum', s: 10 },
  }],
  ['first-six-third', 'first-success', 1, SRC.atp, {
    value: q(25, 216),
    text: 'A die is thrown repeatedly. What is the probability that the first six appears on the third throw?',
    distractors: [
      { value: q(1, 6), misconception: 'Ignored that the first two throws must miss.' },
      { value: q(25, 36), misconception: 'Forgot the final 1/6.' },
      { value: q(91, 216), misconception: 'Computed "a six within three throws".' },
      { value: q(1, 216), misconception: 'Multiplied 1/6 three times.' },
    ],
    steps: steps(['Path: miss, miss, six.', '"First" forces earlier misses.'], ['P = (5/6)² × 1/6 = 25/216 ≈ 0.116.', 'Multiply along the path.']),
    rule: '(1 − p)^(k−1) p.', anchor: 'One trial, repeated with forced failures.',
    hints: ['What must throws 1 and 2 show?', 'Multiply.'], params: { variant: 'onK', a: 1, c: 6, k: 3 },
  }],
  ['flush', 'card-draws', 3, SRC.feller, {
    value: new Q(4n * nCr(13, 5), nCr(52, 5)),
    text: 'Five cards are dealt from a shuffled deck. What is the probability that all five are the same suit?',
    distractors: [
      { value: qpow(q(1, 4), 4), misconception: 'Dealt with replacement.' },
      { value: new Q(nCr(13, 5), nCr(52, 5)), misconception: 'Required one specific suit.' },
      { value: q(12, 51), misconception: 'Only checked the second card.' },
      { value: qpow(q(1, 4), 5), misconception: 'Specific suit, with replacement.' },
    ],
    steps: steps(['First card free; then 12/51 × 11/50 × 10/49 × 9/48.', 'Shrinking suit.'], ['P ≈ 0.00198.', 'About 1 in 505.']),
    rule: 'Flush ≈ 0.002.', anchor: 'Same-suit pair (12/51) extended to five cards.',
    hints: ['Does the first card matter?', 'Four more must match.'], params: { kind: 'flush' },
  }],
  ['walk-back-to-zero', 'random-walk-line', 3, SRC.feller, {
    value: q(252, 1024),
    text: 'A particle starts at 0 and steps +1 or −1 with equal probability. What is the probability it is back at 0 after 10 steps?',
    distractors: [
      { value: q(1, 11), misconception: 'Treated end points as equally likely.' },
      { value: q(1, 32), misconception: 'Required five ups then five downs.' },
      { value: q(1, 2), misconception: 'Coin flip.' },
      { value: q(772, 1024), misconception: 'Answered the complement.' },
    ],
    steps: steps(['Back at 0 ⇔ 5 ups and 5 downs.', 'They cancel.'], ['P = C(10,5)/2^10 = 252/1024 ≈ 0.246.', 'Choose the up-steps.']),
    rule: 'C(2m, m)/4^m.', anchor: 'Exactly 5 heads in 10 flips.',
    hints: ['How many ups?', 'C(10,5).'], params: { kind: 'returnZero', n: 10 },
  }],
  ['distinct-faces-six', 'linearity', 3, SRC.green, {
    ev: true, value: q(6).mul(q(1).sub(qpow(q(5, 6), 6))), minGap: (c) => Math.max(0.04, Math.abs(c) * 0.05),
    text: 'A die is thrown six times. What is the expected number of different faces seen?',
    distractors: [
      { value: 6, misconception: 'Assumed all six faces appear.' },
      { value: 3.5, misconception: 'Used the average face value.' },
      { value: q(6).mul(qpow(q(5, 6), 6)), misconception: 'Computed the expected number of missing faces.' },
      { value: 5, misconception: 'Guessed one repeat.' },
    ],
    steps: steps(['P(face f appears) = 1 − (5/6)^6 ≈ 0.665.', 'Complement of missing on all six throws.'], ['E = 6 × 0.665 ≈ 3.99.', 'Linearity over faces.']),
    rule: 's(1 − (1 − 1/s)^n).', anchor: 'Indicators per face.',
    hints: ['Indicator per face.', 'P(face appears) = 1 − (5/6)^6.'], params: { kind: 'distinct', n: 6, s: 6 },
  }],
  ['ann-first-six', 'first-success', 2, SRC.mosteller, {
    value: q(6, 11),
    text: 'Two players take turns throwing a die; the first to throw a six wins. What is the probability that the player who throws first wins?',
    distractors: [
      { value: q(1, 2), misconception: 'Ignored the first-mover advantage.' },
      { value: q(5, 11), misconception: 'Computed the second player\'s chance.' },
      { value: q(1, 6), misconception: 'Only counted the first throw.' },
      { value: q(11, 36), misconception: 'Computed P(a six in the first round).' },
    ],
    steps: steps(['Per round: first player wins with 1/6, second with 5/36.', 'The second throw counts only after a miss.'], ['Ratio 6 : 5, so P = 6/11 ≈ 0.545.', 'Repeat rounds do not change the ratio.']),
    rule: 'Starter wins 1/(2 − p).', anchor: 'Geometric waiting, split by whose turn it is.',
    hints: ['Compare the chances inside one round.', '1/6 against 5/36.'], params: { variant: 'duel' },
  }],
  ['empty-boxes', 'linearity', 3, SRC.feller, {
    ev: true, value: q(4).mul(qpow(q(3, 4), 4)), minGap: (c) => Math.max(0.04, Math.abs(c) * 0.05),
    text: 'Four balls are thrown independently and uniformly into four boxes. What is the expected number of empty boxes?',
    distractors: [
      { value: 0, misconception: 'Assumed a perfect spread.' },
      { value: qpow(q(3, 4), 4), misconception: 'Gave the probability one box is empty.' },
      { value: q(4).mul(q(1).sub(qpow(q(3, 4), 4))), misconception: 'Counted occupied boxes.' },
      { value: 1, misconception: 'Guessed one.' },
    ],
    steps: steps(['P(box empty) = (3/4)^4 = 81/256.', 'All four balls miss it.'], ['E = 4 × 81/256 = 81/64 ≈ 1.27.', 'Linearity.']),
    rule: 'k(1 − 1/k)^m.', anchor: 'Indicators per box.',
    hints: ['Indicator per box.', 'P(empty) = (3/4)^4.'], params: { kind: 'empty', m: 4, k: 4 },
  }],
  ['stock-hits-ten', 'gamblers-ruin', 2, SRC.prachubStats, {
    value: q(3, 10),
    text: 'A stock at 3 moves up or down 1 each minute with equal probability. What is the probability it reaches 10 before it reaches 0?',
    distractors: [
      { value: q(1, 2), misconception: 'Ignored the starting point.' },
      { value: q(7, 10), misconception: 'Gave the chance of hitting 0 first.' },
      { value: q(3, 7), misconception: 'Used the odds 3 : 7 as a probability.' },
      { value: qpow(q(1, 2), 7), misconception: 'Required seven up-moves in a row.' },
    ],
    steps: steps(['Fair walk: expected level stays at 3.', 'Martingale.'], ['10·P + 0·(1 − P) = 3 → P = 3/10.', 'Solve.']),
    rule: 'Fair ruin: i/N.', anchor: 'Zero expected profit of a fair bet.',
    hints: ['What is conserved in a fair game?', '10P = 3.'], params: { mode: 'fairP', i: 3, N: 10 },
  }],
  ['runs-ten-flips', 'linearity', 2, SRC.feller, {
    ev: true, value: q(11, 2), minGap: (c) => Math.max(0.04, Math.abs(c) * 0.05),
    text: 'A coin is flipped 10 times. What is the expected number of runs (maximal blocks of equal outcomes)?',
    distractors: [
      { value: 5, misconception: 'Forgot the first run.' },
      { value: 2, misconception: 'Assumed one run of each side.' },
      { value: 10, misconception: 'Assumed every flip starts a run.' },
      { value: q(9, 4), misconception: 'Computed expected HH pairs.' },
    ],
    steps: steps(['Runs = 1 + number of changes between neighbours.', 'Each change starts a new run.'], ['9 neighbour pairs, each a change with probability 1/2: E = 1 + 4.5 = 5.5.', 'Linearity.']),
    rule: '(n + 1)/2.', anchor: 'Indicators per neighbouring pair.',
    hints: ['Relate runs to changes.', 'Each pair changes with probability 1/2.'], params: { kind: 'runs', n: 10 },
  }],
  ['four-throws-all-different', 'die-repeats', 2, SRC.atp, {
    value: q(360, 1296),
    text: 'A die is thrown four times. What is the probability that all four faces are different?',
    distractors: [
      { value: q(125, 216), misconception: 'Only required each throw to differ from the previous one.' },
      { value: q(215, 216), misconception: 'Treated "all different" as "not all the same".' },
      { value: q(15, 1296), misconception: 'Counted sets of faces, not sequences.' },
      { value: q(1, 2), misconception: 'Guessed.' },
    ],
    steps: steps(['6/6 × 5/6 × 4/6 × 3/6.', 'Each throw avoids all earlier faces.'], ['P = 360/1296 = 5/18 ≈ 0.278.', 'Multiply.']),
    rule: '6·5·4·3/6^4.', anchor: 'Chain of conditional fractions.',
    hints: ['Fix the first throw.', 'Multiply the allowed fractions.'], params: { kind: 'allDiff', n: 4, k: 6 },
  }],
  ['hundred-doors', 'monty-hall', 3, SRC.monty, {
    value: q(99, 100),
    text: '100 doors hide one car. You pick one; the host, who knows where the car is, opens 98 of the others, all goats. You switch to the last closed door. What is the probability you win?',
    distractors: [
      { value: q(1, 2), misconception: 'Treated the two closed doors as equally likely.' },
      { value: q(1, 100), misconception: 'Gave the staying probability.' },
      { value: q(1, 99), misconception: 'Spread 99/100 over all 99 other doors including opened ones.' },
      { value: 0.9, misconception: 'Guessed a round number.' },
    ],
    steps: steps(['Your door keeps 1/100.', 'The host can always open 98 goats.'], ['The one other closed door holds 99/100.', 'The host never opens the car.']),
    rule: 'Knowing host concentrates (n − 1)/n on the doors he leaves.', anchor: 'The 3-door game scaled up.',
    hints: ['Does the host\'s action change your door?', 'Where does the rest go?'], params: { n: 100, m: 98, variant: 'switch' },
  }],
  ['sum-uniforms', 'uniform-geometry', 2, SRC.green, {
    value: q(1, 2).mul(q(3, 4)).mul(q(3, 4)),
    text: 'X and Y are independent uniform numbers on [0, 1]. What is the probability that X + Y < 3/4?',
    distractors: [
      { value: q(3, 8), misconception: 'Treated X + Y as uniform on [0, 2].' },
      { value: q(9, 16), misconception: 'Forgot the 1/2 in the triangle area.' },
      { value: q(3, 4), misconception: 'Used 3/4 directly.' },
      { value: q(23, 32), misconception: 'Answered the complement.' },
    ],
    steps: steps(['The region x + y < 3/4 is a triangle with legs 3/4.', 'Point in the unit square.'], ['Area = (3/4)²/2 = 9/32 ≈ 0.281.', 'Probability = area.']),
    rule: 's ≤ 1: s²/2.', anchor: 'Lengths become areas.',
    hints: ['Draw the square.', 'Triangle area.'], params: { kind: 'sum', s: 0.75 },
  }],
  ['max-three-uniforms', 'expected-extremes', 3, SRC.green, {
    ev: true, value: q(3, 4),
    text: 'Three numbers are drawn independently and uniformly from [0, 1]. What is the expected value of the largest?',
    distractors: [
      { value: q(1, 2), misconception: 'Used one uniform\'s mean.' },
      { value: q(2, 3), misconception: 'Divided by n instead of n + 1.' },
      { value: q(1, 4), misconception: 'Gave the expected smallest.' },
      { value: q(7, 8), misconception: 'Used 1 − (1/2)³.' },
    ],
    steps: steps(['Three points make four gaps of equal expected length 1/4.', 'Symmetry of spacings.'], ['E[max] = 1 − 1/4 = 3/4.', 'Only the last gap lies above the max.']),
    rule: 'n/(n + 1).', anchor: 'Mean 1/2 = one of two gaps, generalised.',
    hints: ['How many gaps?', 'Each gap averages 1/4.'], params: { mode: 'uniform', which: 'max', n: 3 },
  }],
  ['parity-trap', 'random-walk-line', 3, SRC.feller, {
    value: q(0),
    text: 'A particle starts at 0 and steps +1 or −1 with equal probability. What is the probability that it is at position 3 after 8 steps?',
    distractors: [
      { value: q(1, 9), misconception: 'Treated end points as equally likely.' },
      { value: new Q(nCr(8, 3), 256n), misconception: 'Chose 3 up-steps; the position would be −2.' },
      { value: new Q(nCr(8, 6), 256n), misconception: 'Rounded 5.5 up-steps to 6.' },
      { value: 0.5, misconception: 'Coin flip.' },
      { value: q(70, 256), misconception: 'Computed P(back at 0), a reachable even position.' },
      { value: q(1, 256), misconception: 'Counted a single path.' },
    ],
    steps: steps(['Position = 2u − 8 is always even.', 'Parity of the walk matches the number of steps.'], ['Position 3 is impossible: P = 0.', 'No path reaches it.']),
    rule: 'Wrong parity → probability 0.', anchor: 'Heads count, relabelled as position.',
    hints: ['Can an even number of ±1 steps end at an odd number?', 'Check the parity.'], params: { kind: 'parity', n: 8, k: 3, start: 0 },
  }],
  ['expected-square', 'dice-games-ev', 2, SRC.qbt, {
    ev: true, value: q(91, 6), minGap: (c) => Math.max(0.05, Math.abs(c) * 0.015),
    text: 'A game pays the square of one die\'s face, in dollars. What is the fair price to play?',
    distractors: [
      { value: 12.25, misconception: 'Squared the average (3.5²).' },
      { value: 3.5, misconception: 'Used the average face.' },
      { value: 18.5, misconception: 'Averaged 1 and 36.' },
      { value: 12, misconception: 'Used the continuous formula 6²/3.' },
    ],
    steps: steps(['E[X²] = (1 + 4 + 9 + 16 + 25 + 36)/6.', 'Average the payoffs.'], ['= 91/6 ≈ 15.17.', 'E[X²] − E[X]² = 35/12 is the variance.']),
    rule: 'E[f(X)] ≠ f(E[X]).', anchor: 'Average of a die, applied to the payoff.',
    hints: ['Average the squares.', 'Sum of squares 1..6 = 91.'], params: { kind: 'square', k: 6 },
  }],
  ['numbers-sum-eleven', 'pigeonhole', 2, SRC.mosteller, {
    value: q(1),
    text: 'You pick six different numbers from 1 to 10. What is the probability that two of them add up to 11?',
    distractors: [
      { value: q(55, 63), misconception: 'Used the five-number answer.' },
      { value: 0.5, misconception: 'Coin flip.' },
      { value: q(1, 9), misconception: 'Chance for two particular chosen numbers.' },
      { value: q(2, 3), misconception: 'Estimated without the pigeonhole check.' },
    ],
    steps: steps(['Pairs summing to 11: {1,10}, {2,9}, {3,8}, {4,7}, {5,6}.', 'Five boxes.'], ['Six numbers in five pairs: two share a pair. P = 1.', 'Pigeonhole.']),
    rule: 'Build the boxes, then compare counts.', anchor: 'Coins into boxes, with complementary pairs as boxes.',
    hints: ['Which numbers pair to 11?', '6 numbers, 5 pairs.'], params: { kind: 'pairsSum', N: 5, r: 6 },
  }],
  ['ace-before-king', 'card-symmetry', 2, SRC.mosteller, {
    value: q(1, 2),
    text: 'A deck is dealt face up. What is the probability that the first ace appears before the first king?',
    distractors: [
      { value: q(1, 13), misconception: 'Computed the chance the first card is an ace.' },
      { value: q(3, 14), misconception: 'Required the first two aces-or-kings to both be aces.' },
      { value: q(1, 70), misconception: 'Required all aces before all kings.' },
      { value: q(4, 13), misconception: 'Mixed rank counts.' },
    ],
    steps: steps(['Only the 8 aces and kings matter.', 'Other cards do not change their order.'], ['Each is equally likely to come first among them: 4/8 = 1/2.', 'Symmetry.']),
    rule: 'Relative order of k special cards is uniform.', anchor: 'Uniform position of a card, applied to the relevant subset.',
    hints: ['Which cards decide it?', '4 of 8.'], params: { kind: 'aceBeforeKing' },
  }],
];

for (const [slug, family, difficulty, source, spec] of more) bank.push(mk(slug, family, difficulty, spec, source));

export default bank;
