#!/usr/bin/env node
// Writes two catalogs: src/study/catalog.js (lessons without their text) and
// src/sections/catalog.js (question families and Zap-N games without their generators).
// Today, Progress and Settings import only these, so lesson text and question generators
// load when a page that uses them opens. tests/study/catalog.test.js fails when either is stale.
//   node tools/build-catalog.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ALL_LESSONS } from '../src/study/content/index.js';
import { SECTION_MODULES } from '../src/sections/index.js';
import { GAMES } from '../src/zapn/index.js';

export function catalogSource() {
  const rows = ALL_LESSONS.map(({ id, book, kind, title, family }) => (family ? { id, book, kind, title, family } : { id, book, kind, title }));
  return `// Generated by tools/build-catalog.mjs from src/study/content. Do not edit by hand.
// Every lesson in reading order, without its text; Study loads the text on demand.
export const LESSONS = ${JSON.stringify(rows, null, 0).replace(/\},\{/g, '},\n  {').replace(/^\[\{/, '[\n  {').replace(/\}\]$/, '},\n]')};

// Lessons of one book in reading order (empty for a book still being written).
export const bookLessons = (bookId) => LESSONS.filter((l) => l.book === bookId);

// Section id + family id -> lesson id, for "Learn this" links from practice.
export const lessonForFamily = (sectionId, familyId) => LESSONS.find((l) => l.kind === 'family' && l.book === sectionId && l.family === familyId)?.id ?? null;
`;
}

const lines = (rows) => rows.map((r) => `  ${JSON.stringify(r)},`).join('\n');

export function sectionsCatalogSource() {
  const fams = Object.entries(SECTION_MODULES).map(([sid, mod]) => `  ${sid}: [\n${lines(mod.families.map(({ id, title, skill, levels }) => ({ id, title, skill, levels }))).replace(/^/gm, '  ')}\n  ],`).join('\n');
  return `// Generated by tools/build-catalog.mjs from src/sections and src/zapn. Do not edit by hand.
// Each task's question families and the Zap-N games, without their generators.
export const FAMILIES = {
${fams}
};

export const GAMES = [
${lines(GAMES.map(({ id, title }) => ({ id, title })))}
];

export const familyTitle = (sectionId, familyId) => FAMILIES[sectionId]?.find((f) => f.id === familyId)?.title || familyId;
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(fileURLToPath(new URL('../src/study/catalog.js', import.meta.url)), catalogSource());
  writeFileSync(fileURLToPath(new URL('../src/sections/catalog.js', import.meta.url)), sectionsCatalogSource());
  console.log(`Wrote src/study/catalog.js (${ALL_LESSONS.length} lessons) and src/sections/catalog.js.`);
}
